import { useState } from 'react';
import { Crown, Flame, Pencil, Plus, Shield, ShieldCheck, Trash2, Trophy, UsersRound, Waves } from 'lucide-react';
import { Badge, Button, IconButton, PageHeading, Panel, ProgressBar, StatCard } from '../components/ui';
import { useWorkspace } from '../workspace-context';
import type { Clan } from '../types';
import { formatNumber } from './helpers';
import { ClanEditor } from './modals';
import { ConfirmDelete } from './members';

export function ClanPage() {
  const { data, save, remove } = useWorkspace();
  const [editing, setEditing] = useState<Clan | null | undefined>(undefined);
  const [deleting, setDeleting] = useState<Clan | null>(null);
  if (!data) return null;
  const totalBases = data.members.filter((member)=>member.isActive).length;
  const familyTrophies = data.clans.reduce((sum,clan)=>sum+clan.trophies,0);
  const familyStreak = data.clans.reduce((sum,clan)=>sum+clan.warWinStreak,0);
  const avgClanLevel = data.clans.length ? (data.clans.reduce((sum,clan)=>sum+clan.clanLevel,0)/data.clans.length).toFixed(1) : '0';
  return <div className="page-stack">
    <PageHeading eyebrow="Clan operations · family" title="Your clans" detail="A clear view of every banner, roster and league inside the family." actions={<Button leading={<Plus size={16}/>} onClick={()=>setEditing(null)}>Add clan</Button>} />
    <section className="stat-grid stat-grid--compact"><StatCard icon={<ShieldCheck size={18}/>} label="Clan banners" value={data.clans.length} hint="Family network" tone="gold"/><StatCard icon={<UsersRound size={18}/>} label="Active bases" value={totalBases} hint="Across all rosters" tone="blue"/><StatCard icon={<Trophy size={18}/>} label="Family trophies" value={formatNumber(familyTrophies)} hint="Combined clan points" tone="green"/><StatCard icon={<Flame size={18}/>} label="Total win streak" value={`${familyStreak} wars`} hint={`Average clan level ${avgClanLevel}`} tone="gold"/></section>
    <div className="clan-card-grid">{data.clans.map((clan,index)=>{const members=data.members.filter((member)=>member.clanId===clan.id&&member.isActive);const ready=members.filter((member)=>member.warOptIn&&member.heroReadiness>=76&&member.missedAttacks30d<2).length;const readyPct=members.length?Math.round(ready/members.length*100):0;const leaders=members.filter((member)=>member.role==='leader'||member.role==='co_leader').slice(0,3);return <Panel className={`clan-management-card clan-management-card--${index}`} key={clan.id}><div className="clan-management-card__top"><span className={`family-crest family-crest--${index}`}><Shield size={27} fill="currentColor"/></span><div className="clan-management-card__tags"><Badge tone="gold"><Crown size={12}/> CLAN LEVEL {clan.clanLevel}</Badge><Badge tone={index===0?'gold':index===1?'blue':'green'}>{clan.league}</Badge></div><div className="clan-card-menu"><IconButton label={`Edit ${clan.name}`} onClick={()=>setEditing(clan)}><Pencil size={15}/></IconButton><IconButton label={`Remove ${clan.name}`} onClick={()=>setDeleting(clan)}><Trash2 size={15}/></IconButton></div></div><div className="clan-management-card__identity"><span className="eyebrow">{clan.shortName||clan.tag}</span><h2>{clan.name}</h2><p>{clan.description||'A banner within the clan family.'}</p><span className="clan-tag">{clan.tag}</span></div><div className="clan-management-card__numbers"><div><strong>{members.length}<small>/50</small></strong><span>ROSTER</span></div><div><strong>{formatNumber(clan.trophies)}</strong><span>TROPHIES</span></div><div><strong>{clan.warWinStreak}</strong><span>WIN STREAK</span></div></div><div className="clan-readiness"><div><span><ShieldCheck size={14}/> War readiness</span><b>{readyPct}%</b></div><ProgressBar value={readyPct} tone={readyPct>=78?'green':'gold'} height="md"/><small>{ready} opted-in bases meeting readiness criteria</small></div><div className="clan-management-card__leaders"><span>CLAN LEADERS</span><div>{leaders.map((leader)=><span className="leader-chip" key={leader.id}><i>{leader.name.slice(0,1)}</i>{leader.name}<small>{leader.role==='leader'?'L':'Co'}</small></span>)}{leaders.length===0?<small>Assign leadership in the roster</small>:null}</div></div><div className="clan-management-card__footer"><span><Waves size={14}/> {clan.clanLevel>=25?'Capital focus':clan.clanLevel>=20?'War progression':'Growth roster'}</span><span>Last sync <b>today</b></span></div></Panel>})}</div>
    <Panel className="clan-health-panel"><div className="panel-heading"><div><span className="eyebrow">FAMILY BALANCE</span><h2>Roster distribution</h2></div><Badge tone="green" dot>HEALTHY</Badge></div><div className="clan-distribution">{data.clans.map((clan,index)=>{const count=data.members.filter((member)=>member.clanId===clan.id&&member.isActive).length;const share=totalBases?Math.round(count/totalBases*100):0;return <div className="distribution-row" key={clan.id}><span className={`mini-clan-crest mini-clan-crest--${index}`}><Shield size={15}/></span><span><strong>{clan.name}</strong><small>{count} active bases</small></span><ProgressBar value={share} tone={index===0?'gold':index===1?'blue':'green'}/><b>{share}%</b><span className="distribution-capacity">{Math.max(0,50-count)} open</span></div>})}</div><div className="family-capacity"><span><UsersRound size={14}/> Family roster utilization</span><ProgressBar value={Math.min(100,totalBases/150*100)} tone="gold"/><b>{totalBases} / 150 bases</b></div></Panel>
    {editing!==undefined?<ClanEditor clan={editing} onClose={()=>setEditing(undefined)} onSave={(payload)=>save('clans',editing?.id||null,payload)}/>:null}
    {deleting?<ConfirmDelete title={`Remove ${deleting.name}?`} detail="A clan with players or war history cannot be deleted. Move the roster and archive war records first." onClose={()=>setDeleting(null)} onConfirm={async()=>{try{await remove('clans',deleting.id);setDeleting(null);}catch{}}}/>:null}
  </div>;
}
