import { useState, type FormEvent } from 'react';
import { AlertTriangle, BellRing, Bot, Check, CheckCircle2, Hash, LockKeyhole, Send, ShieldCheck, Swords, Trophy, Webhook, Wifi, X } from 'lucide-react';
import { apiRequest } from '../api';
import { Badge, Button, Field, PageHeading, Panel, Toggle } from '../components/ui';
import { useWorkspace } from '../workspace-context';
import type { DiscordIntegration } from '../types';

const defaultIntegration:DiscordIntegration={id:'discord',enabled:false,guildId:'',channelLabel:'war-room',notifications:{warReminders:true,cwlLineup:true,memberMilestones:true,rankedMovement:false},webhookConfigured:false,updatedAt:''};

export function IntegrationPage(){
  const {data,saveIntegration,notify}=useWorkspace();
  const integration=data?.integration||defaultIntegration;
  const [guildId,setGuildId]=useState(integration.guildId);
  const [channelLabel,setChannelLabel]=useState(integration.channelLabel||'war-room');
  const [enabled,setEnabled]=useState(integration.enabled);
  const [notifications,setNotifications]=useState(integration.notifications);
  const [webhookUrl,setWebhookUrl]=useState('');
  const [removeWebhook,setRemoveWebhook]=useState(false);
  const [saving,setSaving]=useState(false);
  const [testing,setTesting]=useState(false);
  const [testMessage,setTestMessage]=useState('');
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setTestMessage('');const payload:Record<string,unknown>={enabled,guildId,channelLabel,notifications};if(webhookUrl.trim())payload.webhookUrl=webhookUrl.trim();else if(removeWebhook)payload.webhookUrl='';try{await saveIntegration(payload);setWebhookUrl('');setRemoveWebhook(false);}catch{}finally{setSaving(false);}}
  async function testWebhook(){setTesting(true);setTestMessage('');try{const result=await apiRequest<{message:string}>('/api/integrations/discord/test',{method:'POST',body:'{}'});setTestMessage(result.message);notify('Discord webhook test delivered.');}catch(error){const message=error instanceof Error?error.message:'Discord test failed.';setTestMessage(message);notify(message,true);}finally{setTesting(false);}}
  const ready=integration.webhookConfigured;
  return <div className="page-stack integrations-page">
    <PageHeading eyebrow="Clan tools · external connections" title="Discord bot" detail="Send clan alerts and selected milestones into a private Discord channel." actions={<Badge tone={integration.enabled?'green':'muted'} dot>{integration.enabled?'WEBHOOK ACTIVE':'NOT CONNECTED'}</Badge>} />
    <div className="discord-hero"><div className="discord-hero__icon"><Bot size={32}/><span><i/></span></div><div><span className="eyebrow">CLAN COMMAND · DISCORD RELAY</span><h2>{integration.enabled?'Your signals are connected.':'Bring the clan into the loop.'}</h2><p>{integration.enabled?'Configured clan events can now post to the selected Discord channel.':'Connect a Discord webhook to deliver selected alerts to your leadership or war channel.'}</p></div><div className="discord-hero__state"><span className={`discord-signal ${integration.enabled?'discord-signal--on':''}`}><i/></span><span><strong>{integration.enabled?'Connected':'Setup required'}</strong><small>{integration.channelLabel?`#${integration.channelLabel}`:'No channel selected'}</small></span></div></div>
    <div className="integration-grid"><Panel className="discord-setup-panel"><div className="panel-heading"><div><span className="eyebrow">CONNECTION SETTINGS</span><h2>Discord webhook</h2></div><Webhook size={17} className="panel-heading__icon"/></div><form onSubmit={submit}><Field label="Discord server ID (optional)" value={guildId} onChange={(event)=>setGuildId(event.target.value)} placeholder="123456789012345678" hint="Used as an admin reference only; never used to call Discord."/><Field label="Channel label" value={channelLabel} onChange={(event)=>setChannelLabel(event.target.value)} placeholder="war-room" hint="A name for leadership. Webhooks are attached to the channel in Discord."/><label className="form-field"><span>Incoming webhook URL</span><input type="password" autoComplete="new-password" value={webhookUrl} onChange={(event)=>{setWebhookUrl(event.target.value);setRemoveWebhook(false);}} placeholder={ready?'Saved securely · leave blank to keep':'https://discord.com/api/webhooks/…'} /><small>HTTPS Discord webhook endpoints only. The secret is encrypted at rest and never sent back to this page.</small></label>{ready?<div className="webhook-saved"><span><LockKeyhole size={15}/><strong>Webhook saved</strong><small>Credentials are hidden and encrypted.</small></span><button type="button" onClick={()=>{setRemoveWebhook(!removeWebhook);setWebhookUrl('');}}>{removeWebhook?<><X size={13}/> Keep saved</>:<>Remove webhook</>}</button></div>:null}<div className="discord-enable-row"><Toggle label="Enable Discord notifications" detail="Automatic event delivery begins after these settings are saved." checked={enabled} onChange={setEnabled} disabled={!ready&&!webhookUrl.trim()&&!removeWebhook}/></div><div className="integration-form-actions"><Button type="submit" disabled={saving} leading={<Check size={15} />}>{saving?'Saving settings…':'Save connection'}</Button><Button variant="outline" disabled={!ready||testing||!integration.enabled} onClick={()=>void testWebhook()} leading={<Send size={14} />}>{testing?'Sending…':'Send test'}</Button></div>{testMessage?<div className={`integration-test-result ${testMessage.includes('delivered')?'integration-test-result--success':'integration-test-result--error'}`} role="status">{testMessage.includes('delivered')?<CheckCircle2 size={15}/>:<AlertTriangle size={15}/>} {testMessage}</div>:null}</form></Panel>
      <Panel className="discord-notifications"><div className="panel-heading"><div><span className="eyebrow">EVENT ROUTING</span><h2>What gets posted?</h2></div><BellRing size={17} className="panel-heading__icon"/></div><p className="panel-intro">Turn on only the signals your clan wants to see in Discord.</p><div className="notification-settings"><Toggle label="War room alerts" detail="Active war records and battle-day notes." checked={notifications.warReminders} onChange={(value)=>setNotifications({...notifications,warReminders:value})}/><Toggle label="CWL lineup updates" detail="Changes to CWL preparation and lineup activity." checked={notifications.cwlLineup} onChange={(value)=>setNotifications({...notifications,cwlLineup:value})}/><Toggle label="Member milestones" detail="Roster joins, promotions and progression events." checked={notifications.memberMilestones} onChange={(value)=>setNotifications({...notifications,memberMilestones:value})}/><Toggle label="Ranked movement" detail="Promotion and league movement events." checked={notifications.rankedMovement} onChange={(value)=>setNotifications({...notifications,rankedMovement:value})}/></div><div className="notification-save-hint"><span><CheckCircle2 size={14}/></span>Save the connection to apply notification changes.</div></Panel></div>
    <div className="integration-bottom-grid"><Panel className="bot-command-panel"><div className="panel-heading"><div><span className="eyebrow">BOT ROADMAP</span><h2>In-game command bridge</h2></div><Badge tone="orange">NEXT CONNECTOR</Badge></div><p>Webhook delivery is ready for alerts. Interactive Discord slash commands need a Discord application, bot token and deployment target; those credentials are intentionally not requested or stored here.</p><div className="command-samples"><div><span><Hash size={14}/></span><code>/clan roster</code><small>Roster snapshot</small></div><div><span><Swords size={14}/></span><code>/war status</code><small>Battle day view</small></div><div><span><Trophy size={14}/></span><code>/cwl readiness</code><small>Lineup check</small></div></div></Panel><Panel className="integration-security"><span className="integration-security__icon"><ShieldCheck size={20}/></span><span className="eyebrow">CONNECTION SAFETY</span><h3>Private by design.</h3><p>Webhook URLs are encrypted with a server-side key. The browser only sees whether a credential is configured. Clan data is sent to Discord only when the integration is enabled.</p><div className="security-points"><span><CheckCircle2 size={14}/> HTTPS host allowlist</span><span><CheckCircle2 size={14}/> No secret in API responses</span><span><CheckCircle2 size={14}/> Leader-only access</span></div></Panel></div>
    <div className="integration-footnote"><Wifi size={15}/><span>Current storage is this Clan Command instance's SQLite database. Add a persistent disk and stable <code>CLANCMD_APP_SECRET</code> before production use.</span></div>
  </div>;
}
