import { useMemo, useState } from 'react';
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, ExternalLink, Filter, MoreHorizontal, Pencil, Search, Shield, ShieldCheck, Swords, Trash2, Trophy, TrendingUp, UserPlus, UsersRound } from 'lucide-react';
import { Avatar, Badge, Button, EmptyState, IconButton, PageHeading, Panel, ProgressBar, SelectField, StatCard, Toggle } from '../components/ui';
import { useWorkspace } from '../workspace-context';
import type { AppRole, Member } from '../types';
import { longDate, readinessScore, readinessTone, relativeTime, roleName } from './helpers';
import { MemberEditor } from './modals';

const roleRank: Record<AppRole, number> = { member: 1, elder: 2, co_leader: 3, leader: 4 };

export function MembersPage() {
  const { user, data, save, remove } = useWorkspace();
  const [query, setQuery] = useState('');
  const [clanFilter, setClanFilter] = useState('all');
  const [thFilter, setThFilter] = useState('all');
  const [accountFilter, setAccountFilter] = useState('all');
  const [selected, setSelected] = useState<Member | null | undefined>(undefined);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const navigate = useNavigate();
  const canEdit = user ? roleRank[user.role] >= roleRank.co_leader : false;
  const filtered = useMemo(() => (data?.members ?? []).filter((member) => {
    const search = query.trim().toLowerCase();
    const matches = !search || member.name.toLowerCase().includes(search) || member.tag.toLowerCase().includes(search) || member.clanName.toLowerCase().includes(search) || (member.accountType || '').toLowerCase().includes(search);
    return matches && (clanFilter === 'all' || member.clanId === clanFilter) && (thFilter === 'all' || member.townHall === Number(thFilter)) && (accountFilter === 'all' || member.accountType === accountFilter);
  }), [data?.members,query,clanFilter,thFilter,accountFilter]);
  if (!user || !data) return null;
  const activeCount = data.members.filter((member) => member.isActive).length;
  const readyCount = data.members.filter((member) => member.isActive && readinessScore(member,'war').ready).length;
  const optOutCount = data.members.filter((member) => member.isActive && !member.warOptIn).length;
  const townHallLevels = Array.from(new Set(data.members.map((member) => member.townHall))).sort((a,b) => b-a);

  return <div className="page-stack">
    <PageHeading eyebrow="Clan operations · roster" title="The roster" detail="Every base, role and readiness signal across your clan family." actions={<><Button variant="outline" leading={<Filter size={15} />} onClick={() => {setClanFilter('all');setThFilter('all');setAccountFilter('all');setQuery('');}}>Reset filters</Button>{canEdit ? <Button leading={<UserPlus size={16} />} onClick={() => setSelected(null)}>Add player</Button> : null}</>} />
    <div className="stat-grid stat-grid--compact"><StatCard icon={<UsersRound size={18} />} label="Active players" value={`${activeCount} / 150`} hint={`${data.clans.length} family clans`} tone="blue" /><StatCard icon={<ShieldCheck size={18} />} label="War ready" value={`${readyCount} bases`} hint="Scores above readiness threshold" tone="green" /><StatCard icon={<Swords size={18} />} label="Opted out" value={optOutCount} hint="Check in before war search" tone="gold" /></div>
    <Panel className="roster-panel"><div className="roster-toolbar"><div className="roster-toolbar__title"><div><span className="eyebrow">MEMBER DIRECTORY</span><h2>{filtered.length} player{filtered.length===1?'':'s'} <small>in view</small></h2></div><Badge tone="green" dot>SYNCED</Badge></div><div className="roster-filters"><label className="inline-search"><Search size={15} /><input placeholder="Name or player tag" aria-label="Search roster" value={query} onChange={(event)=>setQuery(event.target.value)} /></label><SelectField label="Clan" value={clanFilter} onChange={(event)=>setClanFilter(event.target.value)}><option value="all">All clans</option>{data.clans.map((clan)=><option key={clan.id} value={clan.id}>{clan.shortName || clan.name}</option>)}</SelectField><SelectField label="Town Hall" value={thFilter} onChange={(event)=>setThFilter(event.target.value)}><option value="all">All TH levels</option>{townHallLevels.map((level)=><option key={level} value={level}>Town Hall {level}</option>)}</SelectField><SelectField label="Account type" value={accountFilter} onChange={(event)=>setAccountFilter(event.target.value)}><option value="all">All accounts</option>{Array.from(new Set(data.members.map((member)=>member.accountType||'Main'))).map((type)=><option key={type} value={type}>{type}</option>)}</SelectField></div></div>
      {filtered.length ? <div className="table-scroller"><table className="data-table roster-table"><thead><tr><th>Player base</th><th>Clan &amp; role</th><th>Village</th><th>Ranked</th><th>Readiness</th><th>War status</th><th aria-label="Actions" /></tr></thead><tbody>{filtered.map((member)=>{const ready=readinessScore(member,'war');return <tr key={member.id} className="roster-row" onClick={()=>navigate(`/app/members/${member.id}`)}><td><span className="player-cell"><Avatar name={member.name} size="sm" /><span><strong>{member.name} <Badge tone="muted">{member.accountType||'Main'}</Badge>{!member.isActive?<Badge tone="red">ARCHIVED</Badge>:null}</strong><small>{member.tag}<i> · </i>{relativeTime(member.lastActiveAt)}</small></span></span></td><td><span className="clan-cell"><strong>{member.clanName}</strong><small>{roleName[member.role]}</small></span></td><td><span className="th-cell"><span>TH {member.townHall} · BH {member.builderHall}</span><strong>XP {member.xpLevel}</strong><small>{member.trophies.toLocaleString()} <span>trophies</span></small></span></td><td><span className="rank-cell"><strong>{member.rankedTier}</strong><small><Trophy size={11}/>{member.rankedPoints.toLocaleString()} pts</small></span></td><td><span className="readiness-cell"><span><b>{ready.score}%</b><small>{ready.ready?'Ready':'Review'}</small></span><ProgressBar value={ready.score} tone={readinessTone(ready.score)} /></span></td><td><Badge tone={!member.isActive?'red':member.warOptIn?'green':'muted'} dot>{!member.isActive?'Archived':member.warOptIn?'In war':'Opted out'}</Badge></td><td><div className="row-actions" onClick={(event)=>event.stopPropagation()}>{canEdit ? <><IconButton label={`Edit ${member.name}`} onClick={()=>setSelected(member)}><Pencil size={14}/></IconButton><IconButton label={`Remove ${member.name}`} onClick={()=>setDeleteId(member.id)}><Trash2 size={14}/></IconButton></> : <IconButton label={`View ${member.name}`} onClick={()=>navigate(`/app/members/${member.id}`)}><MoreHorizontal size={16}/></IconButton>}</div></td></tr>})}</tbody></table></div> : <EmptyState icon={<Search size={20}/>} title="No players match these filters" detail="Try a different tag, name, clan or Town Hall level." action={<Button variant="outline" onClick={()=>{setQuery('');setClanFilter('all');setThFilter('all');setAccountFilter('all');}}>Clear filters</Button>} />}
      <div className="table-footer"><span>Showing <b>{filtered.length}</b> of <b>{data.members.length}</b> roster records</span><span>Updated moments ago <i /> <ShieldCheck size={13}/> Leadership view</span></div>
    </Panel>
    {selected !== undefined ? <MemberEditor member={selected} clans={data.clans} userRole={user.role} onClose={()=>setSelected(undefined)} onSave={(payload)=>save('members',selected?.id||null,payload)} /> : null}
    {deleteId ? <ConfirmDelete title="Remove this player?" detail="The base will be removed from the active roster. Linked history and audit records remain." onClose={()=>setDeleteId(null)} onConfirm={async()=>{try{await remove('members',deleteId);setDeleteId(null);}catch{}}} /> : null}
  </div>;
}

export function ConfirmDelete({ title, detail, onClose, onConfirm }:  { title: string; detail: string; onClose: () => void; onConfirm: () => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><section className="confirm-modal" role="dialog" aria-modal="true"><span className="confirm-modal__icon"><Trash2 size={22}/></span><h2>{title}</h2><p>{detail}</p><div className="form-actions"><Button variant="ghost" onClick={onClose} disabled={busy}>Keep record</Button><Button variant="danger" disabled={busy} onClick={async()=>{setBusy(true);await onConfirm();setBusy(false);}}>{busy?'Removing…':'Remove record'}</Button></div></section></div>;
}

export function MemberDetailPage() {
  const { user, data, save } = useWorkspace();
  const { memberId = '' } = useParams();
  const [editing, setEditing] = useState(false);
  const navigate = useNavigate();
  if (!user || !data) return null;
  const member = data.members.find((item)=>item.id===memberId);
  if (!member) return <div className="page-stack"><PageHeading eyebrow="Player dossier" title="Base not found" detail="This player is not in the current roster." actions={<Button variant="outline" leading={<ArrowLeft size={15}/>} onClick={()=>navigate('/app/members')}>Back to roster</Button>} /><EmptyState icon={<Shield size={22}/>} title="No matching base" detail="The player may have been moved or removed." /></div>;
  if(user.role==='member' && member.id!==user.playerId) return <Navigate to={`/app/members/${user.playerId}`} replace/>;
  const canEdit = roleRank[user.role]>=roleRank.co_leader;
  const relatedAccounts = member.personId ? data.members.filter((item)=>item.personId===member.personId) : [];
  const history = data.history.filter((event)=>event.playerId===member.id);
  const heroes = [
    ['Barbarian King','king'],['Archer Queen','queen'],['Grand Warden','warden'],['Royal Champion','champion'],['Minion Prince','prince'],['Dragon Duke','duke'],
  ] as const;
  const heroLevels = member.heroLevels || {king:0,queen:0,warden:0,champion:0,prince:0,duke:0};
  return <div className="page-stack player-dossier-page"><PageHeading eyebrow="Roster · Player dossier" title={member.name} detail={`${member.clanName} · ${roleName[member.role]} · joined ${longDate(member.joinedAt)}`} actions={<><Link to="/app/members" className="btn btn--outline"><ArrowLeft size={15}/> Back to roster</Link>{canEdit?<Button leading={<Pencil size={15}/>} onClick={()=>setEditing(true)}>Edit base</Button>:null}</>} />
    <section className="dossier-hero"><div className="dossier-hero__identity"><Avatar name={member.name} size="lg"/><div><Badge tone={member.isActive?'gold':'red'} dot>{member.isActive?'PLAYER BASE':'ARCHIVED BASE'}</Badge><Badge tone="muted">{member.accountType||'Main'} account</Badge><h2>{member.name}</h2><span className="dossier-tag">{member.tag} <button type="button" onClick={()=>{void navigator.clipboard?.writeText(member.tag);}}>Copy tag</button></span><div className="dossier-chips"><Badge tone="blue">TH {member.townHall}</Badge><Badge tone="blue">BH {member.builderHall}</Badge><Badge tone="muted">XP {member.xpLevel}</Badge><Badge tone="gold"><Trophy size={12}/>{member.trophies.toLocaleString()} home</Badge><Badge tone="gold">{member.builderBaseTrophies.toLocaleString()} builder</Badge><Badge tone="green">{member.league}</Badge></div></div></div><div className="dossier-quick-stats"><div><span>Ranked tier</span><strong>{member.rankedTier}</strong><small>{member.rankedPoints.toLocaleString()} points</small></div><div><span>Reward balance</span><strong>{member.rewardPoints}</strong><small>Clan points</small></div><div><span>Builder Base</span><strong>{member.builderBaseTrophies.toLocaleString()}</strong><small>BH {member.builderHall} · {member.builderBaseLeague}</small></div><div><span>War stars</span><strong>{member.warStars.toLocaleString()}</strong><small>Lifetime total</small></div><div><span>90-day war record</span><strong>{member.warEntries90d??0} entries</strong><small>{member.warAttacks90d??0} attacks · {member.warMissed90d??0} missed</small></div></div>{member.baseLink?<a className="external-game-link" href={member.baseLink} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Open player in Clash</a>:null}</section>
    {canEdit&&relatedAccounts.length>1?<Panel className="account-family-panel"><div className="panel-heading"><div><span className="eyebrow">PERSON GROUP · {member.personId}</span><h2>Linked player bases</h2></div><Badge tone="blue">{relatedAccounts.length} accounts</Badge></div><div className="account-family-list">{relatedAccounts.map((account)=><Link key={account.id} to={`/app/members/${account.id}`} className={account.id===member.id?'account-family-chip account-family-chip--current':'account-family-chip'}><span>{account.name}</span><small>{account.accountType||'Main'} · TH {account.townHall} · {account.clanName}</small></Link>)}</div></Panel>:null}
    <div className="dossier-grid"><Panel className="hero-levels-panel"><div className="panel-heading"><div><span className="eyebrow">HOME VILLAGE · HEROES</span><h2>Hero progression</h2></div><Badge tone={member.heroReadiness>=80?'green':'orange'}>{member.heroReadiness}% ready</Badge></div><div className="hero-level-list">{heroes.map(([name,key],index)=>{const level=Number(heroLevels[key]||0);const maximum=Math.max(level,member.townHall*5-4);return <div className="hero-level-row" key={key}><span className={`hero-level-icon hero-level-icon--${index}`}><Shield size={15}/></span><span><strong>{name}</strong><small>Level {level}</small></span><ProgressBar value={maximum?level/maximum*100:0} tone={level/Math.max(1,maximum)>.8?'green':'gold'}/><b>{maximum?Math.round(level/maximum*100):0}%</b></div>})}</div><div className="hero-level-footnote"><ShieldCheck size={14}/> Readiness is a leadership signal and may differ from in-game max levels.</div></Panel>
      <Panel className="dossier-war-panel"><div className="panel-heading"><div><span className="eyebrow">BATTLE PROFILE</span><h2>War consistency</h2></div><Swords size={18} className="panel-heading__icon"/></div><div className="war-consistency-score"><div><strong>{readinessScore(member,'war').score}</strong><span>/100</span></div><Badge tone={readinessScore(member,'war').ready?'green':'orange'}>{readinessScore(member,'war').ready?'WAR READY':'REVIEW'}</Badge></div><ProgressBar value={readinessScore(member,'war').score} tone={readinessTone(readinessScore(member,'war').score)} height="md"/><div className="consistency-stats"><div><span>War opt-in</span><b>{member.warOptIn?'Available':'Opted out'}</b></div><div><span>CWL opt-in</span><b>{member.cwlOptIn?'Available':'Opted out'}</b></div><div><span>Attacks · 30d</span><b>{member.warAttacks30d}</b></div><div><span>Missed · 30d</span><b className={member.missedAttacks30d?'text-warning':''}>{member.missedAttacks30d}</b></div><div><span>Donation ratio</span><b>{member.donationRatio.toFixed(1)}×</b></div><div><span>Last activity</span><b>{relativeTime(member.lastActiveAt)}</b></div></div>{user.role==='member'&&member.id===user.playerId?<div className="self-opt-ins"><span className="eyebrow">MY BATTLE AVAILABILITY</span><Toggle label="Regular war" detail="Let leadership know if you are available for the next war." checked={member.warOptIn} onChange={(value)=>{void save('members',member.id,{warOptIn:value});}}/><Toggle label="CWL consideration" detail="Share your availability for the current CWL season." checked={member.cwlOptIn} onChange={(value)=>{void save('members',member.id,{cwlOptIn:value});}}/></div>:null}</Panel></div>
    <Panel className="dossier-history"><div className="panel-heading"><div><span className="eyebrow">BASE TIMELINE</span><h2>Progression history</h2></div><Link to="/app/progression" className="panel-link">Family history <ArrowRight size={14}/></Link></div>{history.length?<div className="dossier-history-list">{history.map(event=><div className="dossier-history-row" key={event.id}><span className="dossier-history-dot"/><span><strong>{event.title}</strong><small>{event.details}</small></span><time>{relativeTime(event.createdAt)}</time></div>)}</div>:<EmptyState icon={<TrendingUp size={20}/>} title="No history yet" detail="Progress milestones for this base will appear here."/>}</Panel>
    <div className="dossier-summary-note"><span><ShieldCheck size={15}/></span><p>Leadership notes stay in Clan Command. Player profiles and progression are private to this workspace.</p></div>
    {editing?<MemberEditor member={member} clans={data.clans} userRole={user.role} onClose={()=>setEditing(false)} onSave={(payload)=>save('members',member.id,payload)}/>:null}
  </div>;
}
