import { useState } from 'react';
import { ArrowRight, ArrowUp, Crown, Flame, Gem, Search, Shield, Sparkles, Trophy } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Avatar, Badge, EmptyState, PageHeading, Panel, ProgressBar, StatCard } from '../components/ui';
import { useWorkspace } from '../workspace-context';
import { formatNumber, shortDate } from './helpers';

const tiers=['Legend','Champion','Master','Titan','Crystal','Gold','Silver','Bronze','Unranked'];
const tierTone=(tier:string):'gold'|'blue'|'green'|'orange'|'muted'=>tier==='Legend'||tier==='Champion'?'gold':tier==='Master'||tier==='Titan'?'blue':tier==='Crystal'?'green':tier==='Unranked'?'muted':'orange';

export function RankedPage(){
  const {data}=useWorkspace();
  const [search,setSearch]=useState('');
  const [tierFilter,setTierFilter]=useState('all');
  if(!data)return null;
  const active=data.members.filter((member)=>member.isActive);
  const ranked=active.filter((member)=>member.rankedTier!=='Unranked');
  const avg=ranked.length?Math.round(ranked.reduce((sum,member)=>sum+member.rankedPoints,0)/ranked.length):0;
  const top=[...ranked].sort((a,b)=>b.rankedPoints-a.rankedPoints).slice(0,3);
  const promotionCount=data.history.filter((event)=>event.eventType==='ranked_promotion').length;
  const filtered=active.filter((member)=>{
    const q=search.trim().toLowerCase();
    return (!q||member.name.toLowerCase().includes(q)||member.tag.toLowerCase().includes(q)||member.clanName.toLowerCase().includes(q))&&(tierFilter==='all'||member.rankedTier===tierFilter);
  }).sort((a,b)=>tiers.indexOf(a.rankedTier)-tiers.indexOf(b.rankedTier)||b.rankedPoints-a.rankedPoints);
  const distribution=tiers.slice(0,8).map((tier)=>({tier,count:active.filter((member)=>member.rankedTier===tier).length}));
  const max=Math.max(1,...distribution.map((item)=>item.count));
  return <div className="page-stack ranked-page">
    <PageHeading eyebrow="Growth & recognition · ranked" title="Ranked progression" detail="Follow league position, season movement and the next player climbing the ladder." actions={<Link to="/app/progression" className="btn btn--outline">Progression history <ArrowRight size={15}/></Link>} />
    <section className="ranked-hero"><div className="ranked-hero__copy"><Badge tone="gold" dot>SEASON VII · RANKED MODE</Badge><h2>Every trophy<br/><span>moves the family.</span></h2><p>Celebrate league climbs, spot momentum and keep each clan's ranked push visible.</p><div className="ranked-season-progress"><span>Season ends in <b>12 days</b></span><ProgressBar value={68} tone="gold" height="md"/><small>68% of season elapsed</small></div></div><div className="ranked-hero__emblem"><div className="ranked-emblem-ring"/><span><Trophy size={47}/></span><strong>SEASON<br/>VII</strong><small>IRON CROWN</small></div><div className="ranked-hero__summary"><span className="eyebrow">FAMILY LADDER</span><strong>{ranked.length}<small> / {active.length}</small></strong><span>players ranked</span><i/><span className="ranked-avg"><Trophy size={14}/> {formatNumber(avg)} <small>avg points</small></span></div></section>
    <div className="ranked-stat-grid"><StatCard icon={<Trophy size={18}/>} label="Ranked bases" value={ranked.length} hint={`${active.length-ranked.length} not placed yet`} tone="gold"/><StatCard icon={<Crown size={18}/>} label="Family leader" value={top[0]?.name||'—'} hint={top[0]?`${formatNumber(top[0].rankedPoints)} points`:'No ranked score'} tone="blue"/><StatCard icon={<Flame size={18}/>} label="Promotions logged" value={promotionCount} hint="Saved to family progression" tone="green"/><StatCard icon={<Gem size={18}/>} label="Top clan tier" value={distribution.find((item)=>item.count>0)?.tier||'Unranked'} hint="Highest current placement" tone="gold"/></div>
    <div className="ranked-content-grid"><Panel className="rank-distribution"><div className="panel-heading"><div><span className="eyebrow">TIER DISTRIBUTION</span><h2>Family ladder</h2></div><Badge tone="muted">{ranked.length} PLACED</Badge></div><div className="tier-list">{distribution.map(({tier,count})=><button type="button" key={tier} className={`tier-row ${tierFilter===tier?'tier-row--selected':''}`} onClick={()=>setTierFilter(tierFilter===tier?'all':tier)}><span className={`tier-icon tier-icon--${tier.toLowerCase()}`}><Shield size={14}/></span><span>{tier}</span><ProgressBar value={count/max*100} tone={tierTone(tier)==='gold'?'gold':tierTone(tier)==='blue'?'blue':tierTone(tier)==='green'?'green':'gold'}/><b>{count}</b></button>)}</div><div className="tier-list-footer"><span>Tap a tier to filter players</span><button type="button" onClick={()=>setTierFilter('all')}>Reset</button></div></Panel>
      <Panel className="rank-podium"><div className="panel-heading"><div><span className="eyebrow">CURRENT TOP PUSH</span><h2>Climbing the ranks</h2></div><span className="podium-crown"><Crown size={17}/></span></div>{top.length?<div className="podium-list">{top.map((member,index)=><Link className={`podium-row podium-row--${index+1}`} key={member.id} to={`/app/members/${member.id}`}><span className="podium-place">{index===0?<Crown size={17}/>:String(index+1).padStart(2,'0')}</span><Avatar name={member.name} size="md"/><span className="podium-player"><strong>{member.name}</strong><small>{member.clanName} · TH {member.townHall}</small></span><span className="podium-points"><strong>{formatNumber(member.rankedPoints)}</strong><small>{member.rankedTier}</small></span><ArrowRight size={15}/></Link>)}</div>:<EmptyState icon={<Trophy size={20}/>} title="No ranked placements" detail="Ranked tiers will appear as the family records its season data."/>}<div className="podium-note"><Sparkles size={14}/> Reward milestones can recognize the season's most consistent climb.</div></Panel></div>
    <Panel className="ranked-roster-panel"><div className="roster-toolbar"><div><span className="eyebrow">RANKED ROSTER</span><h2>{filtered.length} player{filtered.length===1?'':'s'} <small>on the ladder</small></h2></div><div className="roster-filters"><label className="inline-search"><Search size={15}/><input placeholder="Search name or tag" value={search} onChange={(event)=>setSearch(event.target.value)}/></label>{tierFilter!=='all'?<Badge tone="gold">{tierFilter}<button className="badge-clear" aria-label="Clear tier filter" onClick={()=>setTierFilter('all')}>×</button></Badge>:null}</div></div>{filtered.length?<div className="table-scroller"><table className="data-table ranked-table"><thead><tr><th>Player</th><th>Clan</th><th>Home league</th><th>Ranked tier</th><th>Points</th><th>Season trend</th><th>Last milestone</th></tr></thead><tbody>{filtered.map((member)=>{const movement=data.history.find((event)=>event.playerId===member.id&&(event.eventType==='ranked_promotion'||event.eventType==='league_change'));return <tr key={member.id}><td><Link className="player-cell player-cell--link" to={`/app/members/${member.id}`}><Avatar name={member.name} size="sm"/><span><strong>{member.name}</strong><small>{member.tag} · TH {member.townHall}</small></span></Link></td><td>{member.clanName}</td><td>{member.league}</td><td><Badge tone={tierTone(member.rankedTier)}>{member.rankedTier}</Badge></td><td><strong className="rank-points">{member.rankedPoints?formatNumber(member.rankedPoints):'—'}</strong></td><td>{movement?<span className="movement-indicator"><ArrowUp size={14}/>{movement.eventType==='ranked_promotion'?'PROMOTED':'MOVED UP'}</span>:<span className="movement-flat">— Steady</span>}</td><td>{movement?shortDate(movement.createdAt):'—'}</td></tr>})}</tbody></table></div>:<EmptyState icon={<Search size={20}/>} title="No ranked players found" detail="Try a different name or clear the selected league tier."/>}<div className="table-footer"><span>Ranked values are current saved records, not live Supercell API data.</span><Link to="/app/progression">See movement history <ArrowRight size={13}/></Link></div></Panel>
  </div>;
}
