import { useState } from 'react';
import { ArrowRight, Award, CircleDollarSign, Gift, Plus, Sparkles, TicketCheck, Trophy, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Avatar, Badge, Button, EmptyState, PageHeading, Panel, StatCard } from '../components/ui';
import { useWorkspace } from '../workspace-context';
import type { AppRole, Reward, RewardClaim } from '../types';
import { formatNumber, relativeTime } from './helpers';
import { RewardEditor, StatusTransition } from './modals';
import { ConfirmDelete } from './members';

const roleRank:Record<AppRole,number>={member:1,elder:2,co_leader:3,leader:4};
const rewardIcon=(category:string)=>category.toLowerCase().includes('war')?<Trophy size={21}/>:category.toLowerCase().includes('magic')?<Sparkles size={21}/>:category.toLowerCase().includes('season')?<Award size={21}/>:<Gift size={21}/>;
const claimTone:Record<RewardClaim['status'],'orange'|'blue'|'green'|'red'>={pending:'orange',approved:'blue',fulfilled:'green',rejected:'red'};

export function RewardsPage(){
  const {user,data,save,remove,claimReward,updateClaim}=useWorkspace();
  const [editing,setEditing]=useState<Reward|null|undefined>(undefined);
  const [deleting,setDeleting]=useState<Reward|null>(null);
  const [busyClaim,setBusyClaim]=useState<string|null>(null);
  if(!user||!data)return null;
  const canManage=roleRank[user.role]>=roleRank.co_leader;
  const player=data.members.find((member)=>member.id===user.playerId);
  const pending=data.claims.filter((claim)=>claim.status==='pending').length;
  const totalPoints=player?.rewardPoints||0;
  async function requestClaim(reward:Reward){setBusyClaim(reward.id);try{await claimReward(reward.id);}catch{}finally{setBusyClaim(null);}}
  async function transition(claimId:string,status:RewardClaim['status']){try{await updateClaim(claimId,status);}catch{}}
  return <div className="page-stack rewards-page">
    <PageHeading eyebrow="Growth & recognition · rewards" title="Clan rewards" detail="Turn dependable attacks, great calls and steady growth into recognition." actions={canManage?<Button leading={<Plus size={15}/>} onClick={()=>setEditing(null)}>Add reward</Button>:<Link className="btn btn--outline" to="/app/progression">View milestones <ArrowRight size={14}/></Link>} />
    <section className="reward-wallet"><div className="reward-wallet__icon"><WalletCards size={27}/></div><div className="reward-wallet__copy"><span className="eyebrow">YOUR REWARD WALLET</span><h2>{player?player.name:'Clan family'} <small>· {player?.clanName||'Clan Command'}</small></h2><p>Earn points through dependable war participation and clan milestones.</p></div><div className="reward-wallet__balance"><span>AVAILABLE POINTS</span><strong>{formatNumber(totalPoints)}<small> pts</small></strong><i><CircleDollarSign size={14}/> {data.claims.filter((claim)=>claim.playerId===user.playerId&&claim.status==='pending').length} requests in review</i></div></section>
    <div className="reward-stat-grid"><StatCard icon={<Gift size={18}/>} label="Rewards available" value={data.rewards.filter((reward)=>reward.isActive).length} hint="Clan reward catalogue" tone="gold"/><StatCard icon={<TicketCheck size={18}/>} label="Awaiting review" value={pending} hint={canManage?'Leadership action queue':'Your pending requests'} tone="blue"/><StatCard icon={<Trophy size={18}/>} label="Fulfilled this season" value={data.claims.filter((claim)=>claim.status==='fulfilled').length} hint="Rewards delivered to players" tone="green"/></div>
    <div className="rewards-layout"><section className="reward-catalog"><div className="section-title-row"><div><span className="eyebrow">THE TROPHY VAULT</span><h2>Claim your next reward</h2></div><Badge tone="gold"><Sparkles size={12}/> POINTS STORE</Badge></div>{data.rewards.filter((reward)=>reward.isActive).length?<div className="reward-card-grid">{data.rewards.filter((reward)=>reward.isActive).map((reward,index)=>{const canAfford=totalPoints>=reward.pointsCost;const outOfStock=reward.inventory>0&&data.claims.filter((claim)=>claim.rewardId===reward.id&&(claim.status==='pending'||claim.status==='approved')).length>=reward.inventory;return <article className={`reward-card reward-card--${index%4}`} key={reward.id}><div className="reward-card__top"><span className="reward-card__icon">{rewardIcon(reward.category)}</span><Badge tone={outOfStock?'red':'muted'}>{outOfStock?'SOLD OUT':reward.inventory?`${reward.inventory} LEFT`:'OPEN'}</Badge></div><span className="reward-category">{reward.category.toUpperCase()}</span><h3>{reward.name}</h3><p>{reward.description}</p><div className="reward-card__footer"><span className="reward-cost"><CircleDollarSign size={15}/><strong>{formatNumber(reward.pointsCost)}</strong><small>PTS</small></span>{canManage?<div className="reward-card__manage"><button type="button" aria-label={`Edit ${reward.name}`} onClick={()=>setEditing(reward)}>Edit</button><button type="button" aria-label={`Delete ${reward.name}`} onClick={()=>setDeleting(reward)}>×</button></div>:<Button size="sm" disabled={!canAfford||outOfStock||busyClaim===reward.id||!player} onClick={()=>void requestClaim(reward)}>{!player?'Link base':outOfStock?'Unavailable':busyClaim===reward.id?'Requesting…':canAfford?'Claim reward':'Need more points'}</Button>}</div>{!canManage&&!canAfford&&player?<div className="reward-card__gap">{formatNumber(reward.pointsCost-totalPoints)} points until you can claim</div>:null}</article>})}</div>:<EmptyState icon={<Gift size={21}/>} title="The vault is empty" detail="Add a reward for the clan to work toward." action={canManage?<Button onClick={()=>setEditing(null)} leading={<Plus size={15}/>}>Add a reward</Button>:null}/>}</section>
      <Panel className="claims-panel"><div className="panel-heading"><div><span className="eyebrow">REQUEST QUEUE</span><h2>{canManage?'Claim approvals':'My reward requests'}</h2></div><Badge tone={pending?'orange':'green'}>{pending} PENDING</Badge></div>{data.claims.length?<div className="claim-list">{data.claims.map((claim)=>{const canAct=canManage;return <article className="claim-row" key={claim.id}><Avatar name={claim.playerName} size="sm"/><div className="claim-row__detail"><strong>{claim.rewardName}</strong><span>{claim.playerName} · {claim.pointsCost} pts</span><small>{relativeTime(claim.requestedAt)}</small></div><div className="claim-row__status"><Badge tone={claimTone[claim.status]} dot>{claim.status}</Badge>{canAct?<StatusTransition claim={claim} onUpdate={(status)=>void transition(claim.id,status)}/>:null}</div></article>})}</div>:<EmptyState icon={<TicketCheck size={20}/>} title="No requests yet" detail="Reward claims and approvals will show up here."/>}<div className="claims-footer"><span>Requests are stored in this clan workspace.</span>{canManage?<span>Rejected claims automatically refund points.</span>:null}</div></Panel></div>
    <div className="rewards-note"><span><Award size={16}/></span><p>Points are an internal recognition system, not in-game currency. Clan leadership controls the catalogue and approves delivery.</p></div>
    {editing!==undefined?<RewardEditor reward={editing} onClose={()=>setEditing(undefined)} onSave={(payload)=>save('rewards',editing?.id||null,payload)}/>:null}
    {deleting?<ConfirmDelete title={`Remove ${deleting.name}?`} detail="Existing requests keep their reward name for history; new claims will no longer be available." onClose={()=>setDeleting(null)} onConfirm={async()=>{try{await remove('rewards',deleting.id);setDeleting(null);}catch{}}}/>:null}
  </div>;
}
