import { useEffect, useState } from 'react';
import { Activity, ClipboardCheck, Database, Edit3, ExternalLink, KeyRound, Plus, RefreshCw, Shield, ShieldCheck, Trash2, UserCog, UsersRound } from 'lucide-react';
import { Avatar, Badge, Button, EmptyState, IconButton, PageHeading, Panel } from '../components/ui';
import { apiRequest } from '../api';
import { useWorkspace } from '../workspace-context';
import type { User } from '../types';
import { longDate, relativeTime, roleName } from './helpers';
import { UserEditor } from './modals';
import { ConfirmDelete } from './members';

type AuditRecord={id:string;action:string;resource:string;entityId:string|null;detail:string;createdAt:string;actor:string|null};

export function SettingsPage(){
  const {user,data,saveUser,removeUser,notify}=useWorkspace();
  const [editing,setEditing]=useState<User|null|undefined>(undefined);
  const [deleting,setDeleting]=useState<User|null>(null);
  const [audit,setAudit]=useState<AuditRecord[]>([]);
  const [loadingAudit,setLoadingAudit]=useState(true);
  useEffect(()=>{let active=true;apiRequest<{items:AuditRecord[]}>('/api/audit').then((result)=>{if(active)setAudit(result.items);}).catch(()=>{if(active)setAudit([]);}).finally(()=>{if(active)setLoadingAudit(false);});return()=>{active=false;};},[]);
  if(!user||!data)return null;
  const currentUser=user;
  const roleCounts=['leader','co_leader','elder','member'].map((role)=>({role,count:data.users.filter((account)=>account.role===role&&account.isActive).length}));
  async function toggleAccount(account:User){if(account.id===currentUser.id){notify('You cannot suspend your current session.',true);return;}try{await saveUser(account.id,{isActive:!account.isActive});}catch{}}
  return <div className="page-stack settings-page">
    <PageHeading eyebrow="Leadership tools · workspace controls" title="Settings & access" detail="Manage portal accounts, permissions and the activity trail for this clan workspace." actions={<Button leading={<Plus size={15}/>} onClick={()=>setEditing(null)}>Invite account</Button>} />
    <div className="settings-stat-grid"><div className="setting-stat"><span><UsersRound size={17}/></span><div><small>ACTIVE PORTAL ACCOUNTS</small><strong>{data.users.filter((account)=>account.isActive).length}</strong></div></div><div className="setting-stat"><span><ShieldCheck size={17}/></span><div><small>LEADERSHIP ACCOUNTS</small><strong>{data.users.filter((account)=>account.isActive&&(account.role==='leader'||account.role==='co_leader')).length}</strong></div></div><div className="setting-stat"><span><Database size={17}/></span><div><small>STORAGE</small><strong>SQLite</strong></div><Badge tone="green" dot>LOCAL</Badge></div><div className="setting-stat"><span><Activity size={17}/></span><div><small>SESSION ROLE</small><strong>{roleName[user.role]}</strong></div></div></div>
    <Panel className="access-panel"><div className="panel-heading"><div><span className="eyebrow">ROLE-BASED ACCESS</span><h2>Who can enter the keep?</h2></div><Badge tone="blue"><KeyRound size={12}/> AUTHENTICATED</Badge></div><div className="role-permission-grid">{roleCounts.map(({role,count})=><div className={`role-permission-card role-permission-card--${role}`} key={role}><span className={`role-seal role-seal--${role}`}><Shield size={16}/></span><strong>{role==='co_leader'?'Co-Leader':role[0].toUpperCase()+role.slice(1)}</strong><small>{count} active account{count===1?'':'s'}</small><p>{role==='leader'?'Full workspace access, clan settings, integrations and account control.':role==='co_leader'?'Roster, war records, alerts, rewards and CWL readiness.':role==='elder'?'Roster visibility, readiness review and progression or alert logging.':'Own base, ranked view, personal history and reward requests.'}</p></div>)}</div><div className="access-note"><ShieldCheck size={15}/><span>Portal permissions are stored separately from in-game roles. Promote a player in-game without granting them website access.</span></div></Panel>
    <Panel className="account-panel"><div className="panel-heading"><div><span className="eyebrow">ACCOUNT DIRECTORY</span><h2>Member access</h2></div><Button variant="outline" leading={<Plus size={14}/>} onClick={()=>setEditing(null)}>Add account</Button></div><div className="account-list">{data.users.map((account)=><article className={`account-row ${!account.isActive?'account-row--disabled':''}`} key={account.id}><Avatar name={account.displayName} size="md"/><div className="account-row__identity"><strong>{account.displayName}{account.id===user.id?<Badge tone="gold">YOU</Badge>:null}</strong><small>{account.email}</small></div><div className="account-row__role"><Badge tone={account.role==='leader'?'gold':account.role==='co_leader'?'blue':account.role==='elder'?'green':'muted'}>{roleName[account.role]}</Badge><small>{account.playerId?data.members.find((member)=>member.id===account.playerId)?.tag||'Linked base':'No linked base'}</small></div><button type="button" className="account-row__status" disabled={account.id===user.id} aria-pressed={account.isActive} onClick={()=>void toggleAccount(account)}><span className={`account-presence ${account.isActive?'account-presence--on':''}`} /><span>{account.isActive?'Active':'Suspended'}</span></button><div className="account-row__created">Added {longDate((account as User & {createdAt?:string}).createdAt)}</div><div className="row-actions"><IconButton label={`Edit ${account.displayName}`} onClick={()=>setEditing(account)}><Edit3 size={15}/></IconButton><IconButton label={`Delete ${account.displayName}`} disabled={account.id===user.id} onClick={()=>setDeleting(account)}><Trash2 size={15}/></IconButton></div></article>)}</div>{!data.users.length?<EmptyState icon={<UserCog size={21}/>} title="No portal accounts yet" detail="Invite a trusted leader or clan member to begin." action={<Button onClick={()=>setEditing(null)} leading={<Plus size={14}/>}>Invite account</Button>}/>:null}</Panel>
    <Panel className="audit-panel"><div className="panel-heading"><div><span className="eyebrow">SECURITY & CHANGE HISTORY</span><h2>Recent activity</h2></div><IconButton label="Refresh audit history" onClick={()=>{setLoadingAudit(true);void apiRequest<{items:AuditRecord[]}>('/api/audit').then(result=>setAudit(result.items)).catch(()=>notify('Audit history could not be refreshed.',true)).finally(()=>setLoadingAudit(false));}}><RefreshCw size={15}/></IconButton></div>{loadingAudit?<div className="audit-loading"><i/><i/><i/></div>:audit.length?<div className="audit-list">{audit.slice(0,12).map((event)=><div className="audit-row" key={event.id}><span className="audit-icon"><ClipboardCheck size={15}/></span><span><strong>{event.actor||'System'} <small>{event.action}</small> {event.resource.replace('_',' ')}</strong><p>{event.detail||event.entityId||'Workspace change'}</p></span><time>{relativeTime(event.createdAt)}</time></div>)}</div>:<EmptyState icon={<ClipboardCheck size={20}/>} title="No audit events yet" detail="Account and leadership changes will show here."/>}<div className="audit-footnote">This feed contains leadership actions only; passwords and webhook credentials are never recorded.</div></Panel>
    <Panel className="database-panel"><span className="database-panel__icon"><Database size={18}/></span><div><span className="eyebrow">PERSISTENT STORAGE</span><h2>Local SQLite database</h2><p>Workspace records are written to this app instance's SQLite file. The demo database is separate from the existing site and any Sheets or Drive files.</p><div className="database-panel__details"><Badge tone="green" dot>CONNECTED</Badge><span>Database: <code>.data/clan-command.sqlite</code></span><span>Backup: pair the database with the encryption key file.</span></div></div><a href="/api/health" target="_blank" rel="noreferrer" className="text-link">Health check <ExternalLink size={13}/></a></Panel>
    {editing!==undefined?<UserEditor account={editing} members={data.members} onClose={()=>setEditing(undefined)} onSave={(payload)=>saveUser(editing?.id||null,payload)}/>:null}
    {deleting?<ConfirmDelete title={`Delete ${deleting.displayName}'s account?`} detail="Their sign-in sessions will end. The player profile remains in the clan roster; you can invite a new account later." onClose={()=>setDeleting(null)} onConfirm={async()=>{try{await removeUser(deleting.id);setDeleting(null);}catch{}}}/>:null}
  </div>;
}
